// src/tools/reportGenerator.ts — generate the daily jobs report markdown

import { format } from "date-fns";
import { JobResult } from "./webSearch.js";
import { SalaryData, formatSalaryRange } from "./salaryResearch.js";

export function generateJobsReport(
  jobs: JobResult[],
  candidateName: string,
  targetRoles: string[],
  targetCompanyTypes: string[],
  salaryData?: SalaryData[]
): string {
  const today = format(new Date(), "MMMM d, yyyy");
  const scoreBar = (score: number) => "█".repeat(score) + "░".repeat(10 - score);

  const jobSections = jobs
    .sort((a, b) => b.alignmentScore - a.alignmentScore)
    .map((job, i) => {
      const salary = salaryData?.[i];
      const salaryRow = salary
        ? `| **Compensation** | ${formatSalaryRange(salary)} _(${salary.sources.join(", ") || "estimated"})_ |`
        : "";

      return `
## ${i + 1}. ${job.title} — ${job.company}

| Field | Details |
|---|---|
| **Location** | ${job.location} |
| **Alignment** | ${scoreBar(job.alignmentScore)} ${job.alignmentScore}/10 |
${salaryRow}
| **Apply** | [View Posting](${job.url}) |

### Role Overview
${job.description}

### Why You're a Strong Fit
${job.whyItFits}

${salary?.notes ? `> 💰 **Comp note:** ${salary.notes}\n` : ""}
---
`;
    }).join("\n");

  return `# Job Search Report
**Generated:** ${today}  
**Candidate:** ${candidateName}  
**Target Roles:** ${targetRoles.join(", ")}  
**Target Companies:** ${targetCompanyTypes.join(", ")}

---

## Top 5 Matched Roles

${jobSections}

## Next Steps
1. Review each role and click the posting link
2. Tailored resumes are in this folder: \`resume-N-company.md\`
3. Cover letters are in this folder: \`cover-N-company.md\`
4. Apply within 48 hours for best response rates
5. Track your applications: \`npm run status\`

---

*Generated by [job-search-agent](https://github.com/yourusername/job-search-agent)*
`;
}
